version: '3.8'

services:
  localstack:
    container_name: localstack_car_dealership
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - localstack_data:/var/lib/localstack
      - ./localstack/init-scripts:/etc/localstack/init/ready.d
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  localstack_data:
